force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Queue</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Restaurant__c/Restaurant__c.object-meta.xml
<CustomObject>
    <label>Restaurant</label>
    <nameField>
        <label>Restaurant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restaurants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Restaurant__c/fields/AverageMealCost__c.field-meta.xml
<CustomField>
    <fullName>AverageMealCost__c</fullName>
    <description>The average meal cost per person.</description>
    <label>Average Meal Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Restaurant__c/fields/CommissionRate__c.field-meta.xml
<CustomField>
    <fullName>CommissionRate__c</fullName>
    <description>The commission rate agreed upon between the restaurant and the training company.</description>
    <label>Commission Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/RestaurantCommissionMetadata__mdt/RestaurantCommissionMetadata__mdt.object-meta.xml
<CustomObject>
    <label>Restaurant Commission Metadata</label>
    <pluralLabel>Restaurant Commissions Metadata</pluralLabel>
</CustomObject>

force-app/main/default/objects/RestaurantCommissionMetadata__mdt/fields/ProbabilityToBuyPerParticipant__c.field-meta.xml
<CustomField>
    <fullName>ProbabilityToBuyPerParticipant__c</fullName>
    <description>The probability that each participant will buy something at any restaurant.</description>
    <label>Probability To Buy Per Participant</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>The training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/CompletionDate__c.field-meta.xml
<CustomField>
    <fullName>CompletionDate__c</fullName>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Restaurant__c.field-meta.xml
<CustomField>
    <fullName>Restaurant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Restaurant</label>
    <referenceTo>Restaurant__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/RestaurantCommission__c.field-meta.xml
<CustomField>
    <fullName>RestaurantCommission__c</fullName>
    <label>Restaurant Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/TrainerContact__c.field-meta.xml
<CustomField>
    <fullName>TrainerContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The trainer that will perform the training</description>
    <label>Trainer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/TrainingCourse__c.field-meta.xml
<CustomField>
    <fullName>TrainingCourse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Course</label>
    <referenceTo>TrainingCourse__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingCourse__c/TrainingCourse__c.object-meta.xml
<CustomObject>
    <label>Training Course</label>
    <nameField>
        <label>Training Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TrainingService.cls
public with sharing class TrainingService {

    public static final String TRAINING_STATUS_SCHEDULED = 'Scheduled';
    public static final String TRAINING_STATUS_FINISHED = 'Finished';
    public static final String TASK_STATUS_NOT_STARTED = 'Not Started';
    public static final String TASK_PRIORITY = 'Normal';
    public static final String TASK_SUBJECT = 'Reminder: ';
    public static final String TASK_DESCRIPTION = 'This task is just a reminder that a new course is about to start.';

    public void setRestaurantCommissionOnTrainings(List<Training__c> newList, Map<Id, Training__c> oldMap) {
        Map<Id, Restaurant__c> restaurants = trainingRestaurants(newList);
        RestaurantCommissionMetadata__mdt restaurantCommissionMetadata = queryRestaurantCommissionMetadata();        

        for(Training__c training : newList) {
            Decimal commission = calculateCommissionOnTraining(training, restaurants, restaurantCommissionMetadata);
            training.RestaurantCommission__c = commission;
        }
    }

    private Map<Id, Restaurant__c> trainingRestaurants(List<Training__c> trainings) {
        Set<Id> restaurantIds = new Set<Id>();
        
        for(Training__c training : trainings) {
            restaurantIds.add(training.Restaurant__c);
        }

        return new Map<Id, Restaurant__c>(queryTrainingRestaurantsById(restaurantIds));
    }

    private Decimal calculateCommissionOnTraining(
        Training__c training, 
        Map<Id, Restaurant__c> restaurants, 
        RestaurantCommissionMetadata__mdt restaurantCommissionMetadata
    ) {
        Integer numberOfParticipants = training.Participants__r.isEmpty() ? 1 : training.Participants__r.size();
        Integer trainingDays = training.StartDate__c.Date().daysBetween(training.EndDate__c.Date()) + 1;
        Decimal probabilityToBuy = restaurantCommissionMetadata.ProbabilityToBuyPerParticipant__c / 100;
        Restaurant__c restaurant = restaurants.get(training.Restaurant__c);
        Decimal commissionRate = 1.00;
        Decimal averageMealCost = 1.00;

        if(restaurant != null) {
            commissionRate = restaurant.CommissionRate__c / 100;
            averageMealCost = restaurant.AverageMealCost__c;
        }

        return numberOfParticipants * trainingDays * commissionRate * probabilityToBuy * averageMealCost;
    }

    public void insertTasksForTrainings(List<Training__c> newList, Map<Id, Training__c> oldMap) {
        List<Task> tasksToInsert = new List<Task>();

        for(Training__c training : newList) {
            Task task = createTaskForTrainer(training);
            tasksToInsert.add(task);
        }

        if(!tasksToInsert.isEmpty()) {
            insert tasksToInsert;
        }
    }

    private Task createTaskForTrainer(Training__c training) {
        Task task = new Task();

        task.ActivityDate = System.today();
        task.Status = TASK_STATUS_NOT_STARTED;
        task.Priority = TASK_PRIORITY;
        task.Subject = TASK_SUBJECT + training.Name;
        task.Description = TASK_DESCRIPTION;
        task.WhoId = training.TrainerContact__c;
        task.WhatId = training.TrainingCourse__c;

        return task;
    }

    public void updateCompletedTrainings(List<Training__c> newList, Map<Id, Training__c> oldMap) {
        List<Training__c> completedTrainings = new List<Training__c>();

        for(Training__c training : newList) {
            Boolean isJustCompleted = training.Status__c == TRAINING_STATUS_FINISHED && 
                                      oldMap.get(training.Id).Status__c != TRAINING_STATUS_FINISHED;

            if(isJustCompleted) {
                training.CompletionDate__c = System.today();
                completedTrainings.add(training);
            }
        }

        updateParticipantStatus(completedTrainings);
    }

    private void updateParticipantStatus(List<Training__c> trainings) {
        List<Participant__c> participantsToUpdate = new List<Participant__c>();
        List<Participant__c> participants = queryParticipantsByTrainingAndStatus(trainings);

        for(Participant__c participant : participants) {
            participant.Status__c = 'Participated';
            participantsToUpdate.add(participant);
        }

        if(!participantsToUpdate.isEmpty()) {
            update participantsToUpdate;
        }
    }

    public List<Restaurant__c> queryTrainingRestaurantsById(Set<Id> ids) {
        return [SELECT Id, Name, AverageMealCost__c, CommissionRate__c FROM Restaurant__c WHERE Id IN :ids];
    }

    public RestaurantCommissionMetadata__mdt queryRestaurantCommissionMetadata() {
       return [SELECT ProbabilityToBuyPerParticipant__c FROM RestaurantCommissionMetadata__mdt LIMIT 1];
    }

    public List<Participant__c> queryParticipantsByTrainingAndStatus(List<Training__c> trainings) {
        return [
            SELECT Id, Name, Status__c, Training__c
            FROM Participant__c
            WHERE Training__c IN :trainings AND Status__c != 'Participated'
        ];
    }

}