force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>The training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RegistrationConfirmationQueueable.cls
public class RegistrationConfirmationQueueable implements Queueable, Database.AllowsCallouts {

    private List<Training__c> trainings;

    public RegistrationConfirmationQueueable(List<Training__c> trainings) {
        this.trainings = trainings;
    }

    /**
     * This method is part of the Participant registration confirmation process. It is called from the 
     * queueable class, "RegistrationConfirmationQueueable," which is called from the "ParticipantService" 
     * class.
     */
    public void execute(QueueableContext context) {
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        List<Participant__c> participantsToUpdate = new List<Participant__c>();

        for(Training__c training : trainings) {
            for(Participant__c participant : training.Participants__r) {
                HttpResponse response = PaymentLinkCallout.doPaymentCalloutForParticipant(participant);
                String paymentLink = parsePaymentLink(response);
                System.debug('paymentLink: ' + paymentLink);
                participant.PaymentLink__c = paymentLink;
                participantsToUpdate.add(participant);
                
                emails.add(EmailService.createParticipantConfirmationEmail(training, participant));
            }
        }

        if(!emails.isEmpty()) {
            Messaging.sendEmail(emails);
        }

        if(!participantsToUpdate.isEmpty()){
            update participantsToUpdate;
        }
    }

    private String parsePaymentLink(HttpResponse response) {
        String paymentLink = '';

        Map<String, Object> paymentObject = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
        if(!paymentObject.containsKey('payer')) {
            return '';
        }

        Map<String, Object> payer = (Map<String, Object>) paymentObject.get('payer');
        if(!payer.containsKey('link')) {
            return '';
        }

        return (String) payer.get('link');
    }

}