force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Queue</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/TrainingInvoice__c.object-meta.xml
<CustomObject>
    <label>Training Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Training Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingInvoice__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/TrainingRefund__c.object-meta.xml
<CustomObject>
    <label>Training Refund</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Training Refund Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Refunds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingRefund__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <label>Invoice Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Training Refunds</relationshipLabel>
    <relationshipName>TrainingRefunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/RefundDate__c.field-meta.xml
<CustomField>
    <fullName>RefundDate__c</fullName>
    <label>Refund Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/RefundId__c.field-meta.xml
<CustomField>
    <fullName>RefundId__c</fullName>
    <label>Refund Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/TrainingInvoice__c.field-meta.xml
<CustomField>
    <fullName>TrainingInvoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Training Invoice</label>
    <referenceTo>TrainingInvoice__c</referenceTo>
    <relationshipLabel>Training Refunds</relationshipLabel>
    <relationshipName>TrainingRefunds</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/VerificationId__c.field-meta.xml
<CustomField>
    <fullName>VerificationId__c</fullName>
    <label>Verification Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Persistance/TrainingRefundQueries.cls
public with sharing class TrainingRefundQueries {

    public static TrainingRefund__c queryRefundByRefundId(String refundId) {
        return [
            SELECT Id, Name, RefundId__c, RefundDate__c, TrainingInvoice__c, TrainingInvoice__r.InvoiceId__c, 
                   Status__c, VerificationId__c, Participant__c 
            FROM TrainingRefund__c 
            WHERE RefundId__c = :refundId
        ];
    }

}