force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Queue</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>The training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/TrainerContact__c.field-meta.xml
<CustomField>
    <fullName>TrainerContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The trainer that will perform the training</description>
    <label>Trainer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TrainingReminderScheduledTest.cls
@IsTest
public class TrainingReminderScheduledTest {

    @TestSetup
    static void setup() {
        Test.setMock(HttpCalloutMock.class, new PaymentLinkHttpCalloutMock());
        
        Contact contact1 = new Contact(FirstName = 'Trainer', LastName = 'Name', Email = 'test@test.com');
        Contact contact2 = new Contact(FirstName = 'Participant', LastName = 'Name', Email = 'test@test.com');
        List<Contact> contacts = new List<Contact> {contact1, contact2};
        insert contacts;

        Training__c training = new Training__c();
        training.Name = 'Scheduled Training';
        training.TrainerContact__c = contact1.Id;
        training.StartDate__c = System.now().addDays(3);
        training.EndDate__c = System.now().addDays(3);
        training.Status__c = 'Scheduled';
        insert training;

        Participant__c participant = new Participant__c();
        participant.Contact__c = contact2.Id;
        participant.Status__c = ParticipantService.PARTICIPANT_STATUS_ACTIVE;
        participant.Training__c = training.Id;
        insert participant;
    }

    @IsTest
    static void execute_UnitTest() {
        TrainingReminderScheduled reminder = new TrainingReminderScheduled();
        Test.startTest();
        reminder.execute(null);
        Integer invocations = Limits.getEmailInvocations();
        Test.stopTest();

        Assert.isTrue(invocations > 0);
    }

    @IsTest
    static void scheduler_UnitTest() {
        TrainingReminderScheduled reminder = new TrainingReminderScheduled();
        String cronExpression = '0 0 0 ? * * *';

        Test.startTest();
        String jobId = System.schedule('Training Reminder Emails', cronExpression, reminder);
        Test.stopTest();

        CronTrigger cronTrigger = [
            SELECT Id, CronExpression, TimesTriggered, NextFireTime 
            FROM CronTrigger 
            WHERE Id = :jobId
        ];
        Assert.areEqual(cronExpression, cronTrigger.CronExpression);
        Assert.areEqual(0, cronTrigger.TimesTriggered);
    }

    @IsTest
    static void queryTrainingsWithParticipantsByIdAndDate_UnitTest() {
        Integer daysToAdd = 3;
        Integer expectedSize = 1;

        Training__c training = new Training__c();
        training.Name = 'Unqualified Training';
        training.StartDate__c = System.now().addDays(daysToAdd * (-1));
        training.EndDate__c = System.today().addDays(daysToAdd * (-1));
        insert training;

        Date inThreeDays = System.today().addDays(daysToAdd);
        Test.startTest();
        List<Training__c> trainings = TrainingQueries.queryTrainingsWithParticipantsByIdAndDate(inThreeDays);
        Test.stopTest();

        Assert.areEqual(expectedSize, trainings.size());
        Assert.areNotEqual(training.Name, trainings.get(0).Name);
    }

}