force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/ErpId__c.field-meta.xml
<CustomField>
    <fullName>ErpId__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Queue</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Business/Batch/ParticipantSyncBatch.cls
global with sharing class ParticipantSyncBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {

    private String objName;

    global ParticipantSyncBatch(String objName) {
        this.objName = objName;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id, Name, Status__c, ErpId__c FROM ' + objName + ' WHERE ErpId__c = null');
    }

    /**
     * This method is part of the Participant to ERP syncing process. It is called from the scheduled class,
     * "ParticipantSyncScheduled." It updates the participants that have been successfully saved to the ERP system.
     */
    global void execute(Database.BatchableContext bc, List<Participant__c> participants) {
        ParticipantService service = new ParticipantService();
        List<Participant__c> participantsToUpdate = service.sendParticipantToERP(participants);

        if(!participantsToUpdate.isEmpty()){
            update participantsToUpdate;
        }
    }

    global void finish(Database.BatchableContext bc) {}

}