force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingInvoice__c/TrainingInvoice__c.object-meta.xml
<CustomObject>
    <label>Training Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Training Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingInvoice__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/TrainingRefund__c.object-meta.xml
<CustomObject>
    <label>Training Refund</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Training Refund Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Refunds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingRefund__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <label>Invoice Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Training Refunds</relationshipLabel>
    <relationshipName>TrainingRefunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Schedule Change</fullName>
            </value>
            <value>
                <fullName>Course Cancellation</fullName>
            </value>
            <value>
                <fullName>Participant Withdrawal</fullName>
            </value>
            <value>
                <fullName>Technical Issues</fullName>
            </value>
            <value>
                <fullName>Billing Error</fullName>
            </value>
            <value>
                <fullName>Other (Specify in Comments)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/RefundDate__c.field-meta.xml
<CustomField>
    <fullName>RefundDate__c</fullName>
    <label>Refund Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/TrainingInvoice__c.field-meta.xml
<CustomField>
    <fullName>TrainingInvoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Training Invoice</label>
    <referenceTo>TrainingInvoice__c</referenceTo>
    <relationshipLabel>Training Refunds</relationshipLabel>
    <relationshipName>TrainingRefunds</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Tests/RefundCalloutTest.cls
@IsTest
public class RefundCalloutTest {

    @IsTest
    static void doRefundCalloutForParticipant_UnitTest() {
        Test.setMock(HttpCalloutMock.class, new RefundCalloutHttpCalloutMock());

        TrainingRefund__c refund = new TrainingRefund__c();

        refund.TrainingInvoice__r = new TrainingInvoice__c(InvoiceId__c = '659225a2702872fa2a7b59b7');
        refund.Amount__c = 190;
        refund.Participant__c = 'a038b00000XpnwpAAB';
        refund.Reason__c = 'Technical Issues';
        refund.RefundDate__c = System.today();

        Test.startTest();
        RefundCallout.RefundResponseBody responseBody = RefundCallout.doRefundCalloutForParticipant(refund);
        Test.stopTest();

        Assert.areEqual(InvoiceCalloutHttpCalloutMock.AUTH_RESPONSE_TOKEN, responseBody.token);
        Assert.areEqual(RefundCalloutHttpCalloutMock.REFUND_RESPONSE_ID, responseBody.refund_id);
    }

    @IsTest
    static void doGetRefundCalloutForParticipantByRefundId_UnitTest() {
        Test.setMock(HttpCalloutMock.class, new RefundCalloutHttpCalloutMock());
        
        String refundId = RefundCalloutHttpCalloutMock.REFUND_RESPONSE_ID;
        String token = InvoiceCalloutHttpCalloutMock.AUTH_RESPONSE_TOKEN;

        Test.startTest();
        String responseStatus = RefundCallout.doGetRefundCalloutForParticipantByRefundId(refundId, token);
        Test.stopTest();

        Assert.areEqual(RefundCalloutHttpCalloutMock.REFUND_RESPONSE_STATUS, responseStatus);
    }

    @IsTest
    static void doRefundVerificationCalloutForParticipant_UnitTest() {
        Test.setMock(HttpCalloutMock.class, new RefundCalloutHttpCalloutMock());

        String refundId = RefundCalloutHttpCalloutMock.REFUND_RESPONSE_ID;
        String token = InvoiceCalloutHttpCalloutMock.AUTH_RESPONSE_TOKEN;

        Test.startTest();
        String responseVerificationId = RefundCallout.doRefundVerificationCalloutForParticipant(refundId, token);
        Test.stopTest();

        Assert.areEqual(RefundCalloutHttpCalloutMock.VERIFICATION_RESPONSE_ID, responseVerificationId);
    }

}