force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Queue</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>The training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/TrainingInvoice__c.object-meta.xml
<CustomObject>
    <label>Training Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Training Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingInvoice__c/fields/GrandTotal__c.field-meta.xml
<CustomField>
    <fullName>GrandTotal__c</fullName>
    <label>Grand Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/PaymentDate__c.field-meta.xml
<CustomField>
    <fullName>PaymentDate__c</fullName>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/PaymentId__c.field-meta.xml
<CustomField>
    <fullName>PaymentId__c</fullName>
    <label>Payment Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/PaymentLink__c.field-meta.xml
<CustomField>
    <fullName>PaymentLink__c</fullName>
    <label>Payment Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <inlineHelpText>Total isolated tax amount calculated from the total price.</inlineHelpText>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Training Invoices</relationshipLabel>
    <relationshipName>TrainingInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Business/Queueable/InvoicePostProcessingQueueable.cls
public with sharing class InvoicePostProcessingQueueable implements Queueable {

    public static final String INVOICE_STATUS_CREATED = 'Created';
    public static final String INVOICE_STATUS_PAID = 'Paid';
    public static final String INVOICE_STATUS_FAILED = 'Failed';
    public static final String INVOICE_STATUS_REFUNDED = 'Refunded';
    public static final String PARTICIPANT_STATUS_ACTIVE = 'Active';

    private InvoiceRestService.InvoiceRequestBody parsedInvoice;
    
    public InvoicePostProcessingQueueable(InvoiceRestService.InvoiceRequestBody parsedInvoice) {
        this.parsedInvoice = parsedInvoice;
    }

    public void execute(QueueableContext context) {
        TrainingInvoice__c invoice = new TrainingInvoice__c();
        Participant__c participant = new Participant__c();

        if(parsedInvoice.status == INVOICE_STATUS_CREATED) {
            Id participantId = parsedInvoice.participant_id;

            Training__c training = TrainingQueries.queryTrainingByParticipantId(participantId);

            invoice.InvoiceDate__c = System.today();
            invoice.InvoiceId__c = parsedInvoice.invoice_id;
            invoice.Participant__c = parsedInvoice.participant_id;
            invoice.PaymentId__c = parsedInvoice.payment_id;
            invoice.PaymentLink__c = parsedInvoice.payment_link;
            invoice.Status__c = parsedInvoice.status;
            invoice.GrandTotal__c = parsedInvoice.price;
            invoice.Tax__c = parsedInvoice.tax;
            invoice.Training__c = training.Id;

            participant = training.Participants__r[0];
            participant.PaymentLink__c = parsedInvoice.payment_link;

            List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
            emails.add(EmailService.createParticipantPaymentEmail(training, participant));

            if(!emails.isEmpty()) {
                Messaging.sendEmail(emails);
            }
        } else if(parsedInvoice.status == INVOICE_STATUS_PAID) {
            invoice.PaymentDate__c = System.today();
            invoice.InvoiceId__c = parsedInvoice.invoice_id;
            invoice.Status__c = parsedInvoice.status;

            participant = ParticipantQueries.queryParticipantByInvoiceId(parsedInvoice.invoice_id);
            participant.Status__c = PARTICIPANT_STATUS_ACTIVE;
        } 

        try {
            upsert invoice InvoiceId__c;

            update participant;
        } catch(Exception e) {
            Logger logger = new Logger();
            logger.logException(e);
        }
    }

}