force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Tests/LoggerTest.cls
@IsTest
public with sharing class LoggerTest {

    @TestSetup
    static void setup() {
    }

    @IsTest
    static void logException_UnitTest() {
        try {
            Participant__c participant = [SELECT Id FROM Participant__c WHERE Id = NULL];
        } catch(Exception e) {
            Logger logger = new Logger();
            logger.logException(e);
        }

        ErrorLog__c insertedLog = [
            SELECT Id, ClassName__c, MethodName__c, ExceptionType__c, ExceptionMessage__c, LineNumber__c
            FROM ErrorLog__c LIMIT 1
        ];
        Assert.isNotNull(insertedLog);
        Assert.isTrue(insertedLog.ClassName__c.contains('LoggerTest'));
        Assert.isTrue(insertedLog.MethodName__c.contains('logException_UnitTest'));
        Assert.areEqual(11, insertedLog.LineNumber__c);
    }

}