force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/Important__c.field-meta.xml
<CustomField>
    <fullName>Important__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Important</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ErrorLogCleanupMetadata__mdt/ErrorLogCleanupMetadata__mdt.object-meta.xml
<CustomObject>
    <label>Error Log Cleanup Metadata</label>
    <pluralLabel>Error Log Cleanup Metadata</pluralLabel>
</CustomObject>

force-app/main/default/objects/ErrorLogCleanupMetadata__mdt/fields/RetentionDays__c.field-meta.xml
<CustomField>
    <fullName>RetentionDays__c</fullName>
    <description>Minimum number of days an Error Log record must be older than to qualify for scheduled deletion</description>
    <label>Retention Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ErrorLogCleanupBatchTest.cls
@IsTest
public with sharing class ErrorLogCleanupBatchTest {

    @TestSetup
    static void setup() {
        List<ErrorLog__c> errorLogs = new List<ErrorLog__c>();

        for(Integer i = 0; i < 20; i++) {
            ErrorLog__c log = new ErrorLog__c();

            if(Math.mod(i, 2) == 0) {
                log.Name = 'Important Log ' + i;
                log.Important__c = true;
            } else {
                log.Name = 'Unimportant Log ' + i;
                log.Important__c = false;
            }

            errorLogs.add(log);
        }

        insert errorLogs;

        for(ErrorLog__c log : errorLogs) {
            Test.setCreatedDate(log.Id, Date.today().addDays(-100));
        }

        update errorLogs;
    }

    @IsTest
    static void executeBatch_UnitTest() {
        ErrorLogCleanupMetadata__mdt ErrorLogCleanupMdt = ErrorLogCleanupMetadataQueries.queryErrorLogCleanupMetadata();
        Date retentionDate = System.today().addDays(ErrorLogCleanupMdt.RetentionDays__c.intValue());
        List<ErrorLog__c> importantLogs = [SELECT Id, Important__c FROM ErrorLog__c WHERE Important__c = true];

        Test.startTest();
        Database.executeBatch(new ErrorLogCleanupBatch());
        Test.stopTest();

        List<ErrorLog__c> retainedLogs = [SELECT Id, CreatedDate, Important__c FROM ErrorLog__c];
        Assert.areEqual(importantLogs.size(), retainedLogs.size());
    }

}