force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/Important__c.field-meta.xml
<CustomField>
    <fullName>Important__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Important</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ErrorLogCleanupMetadata__mdt/ErrorLogCleanupMetadata__mdt.object-meta.xml
<CustomObject>
    <label>Error Log Cleanup Metadata</label>
    <pluralLabel>Error Log Cleanup Metadata</pluralLabel>
</CustomObject>

force-app/main/default/objects/ErrorLogCleanupMetadata__mdt/fields/RetentionDays__c.field-meta.xml
<CustomField>
    <fullName>RetentionDays__c</fullName>
    <description>Minimum number of days an Error Log record must be older than to qualify for scheduled deletion</description>
    <label>Retention Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Business/Batch/ErrorLogCleanupBatch.cls
public with sharing class ErrorLogCleanupBatch implements Database.Batchable<sObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        ErrorLogCleanupMetadata__mdt ErrorLogCleanupMdt = ErrorLogCleanupMetadataQueries.queryErrorLogCleanupMetadata();
        Date retentionDate = System.today().addDays(ErrorLogCleanupMdt.RetentionDays__c.intValue() * -1);

        String querySelect = 'SELECT Id, CreatedDate, Important__c ';
        String queryFrom = 'FROM ErrorLog__c ';
        String queryWhere = 'WHERE CreatedDate < :retentionDate AND Important__c = false';
        String query = querySelect + queryFrom + queryWhere;

        return Database.getQueryLocator(query);
    }

    /**
     * This method is part of the API call error logging cleanup process. It is called from the scheduled class,
     * "ErrorLogCleanupScheduled." It deletes all records older than the specified retention period.
     */
    public void execute(Database.BatchableContext bc, List<ErrorLog__c> errorLogs) {
        if(!errorLogs.isEmpty()) {
            delete errorLogs;
            DataBase.emptyRecycleBin(errorLogs);
        }
    }

    public void finish(Database.BatchableContext bc) {}

}