force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Business/Service/Logger.cls
public with sharing class Logger {

    /**
     * This method is part of the general logging process. It is called from the sendParticipantToERP method 
     * in the "ParticipantService" class and the execute method in the "RegistrationConfirmationQueueable" 
     * queueable class. It accepts an exception and inserts the error log.
     */
    public void logException(Exception e) {
        ErrorLog__c log = createErrorLog(e);
        insert log;
    }

    /**
     * This method is part of the API callout logging process. It is called from the sendParticipantToERP 
     * method in the "ParticipantService" class and the execute method in the "RegistrationConfirmationQueueable" 
     * queueable class. It accepts an exception and inserts the error log.
     */
    public void logCalloutException(Exception e) {
        ErrorLog__c log = createErrorLog(e);
        insert log;
    }

    private ErrorLog__c createErrorLog(Exception e) {
        ErrorLog__c log = new ErrorLog__c();

        log.ClassName__c = parseClassName(e.getStackTraceString());
        log.MethodName__c = parseMethodName(e.getStackTraceString());
        log.ExceptionType__c = e.getTypeName();
        log.ExceptionMessage__c = e.getMessage();
        log.LineNumber__c = e.getLineNumber();
        log.StackTrace__c = e.getStackTraceString();

        return log;
    }

    private String parseClassName(String trace) {
        return trace.split('\n')[0].substringBetween('.', '.');
    }

    private String parseMethodName(String trace) {
        return trace.split('\n')[0].substringAfterLast('.').substringBefore(':');
    }

}