force-app/main/default/objects/TrainingInvoice__c/TrainingInvoice__c.object-meta.xml
<CustomObject>
    <label>Training Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Training Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingInvoice__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/TrainingRefund__c.object-meta.xml
<CustomObject>
    <label>Training Refund</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Training Refund Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Refunds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingRefund__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <label>Invoice Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/RefundId__c.field-meta.xml
<CustomField>
    <fullName>RefundId__c</fullName>
    <label>Refund Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/TrainingInvoice__c.field-meta.xml
<CustomField>
    <fullName>TrainingInvoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Training Invoice</label>
    <referenceTo>TrainingInvoice__c</referenceTo>
    <relationshipLabel>Training Refunds</relationshipLabel>
    <relationshipName>TrainingRefunds</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/VerificationId__c.field-meta.xml
<CustomField>
    <fullName>VerificationId__c</fullName>
    <label>Verification Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Business/Queueable/RefundPostProcessingQueueable.cls
public with sharing class RefundPostProcessingQueueable implements Queueable, Database.AllowsCallouts {

    public static final String REFUND_STATUS_FAILED = 'Failed';
    public static final String REFUND_STATUS_REFUNDED = 'Refunded';

    private TrainingRefund__c refund;
    private String refundId;
    private String refundStatus;
    private String token;
    private String invoiceId;

    public RefundPostProcessingQueueable(TrainingRefund__c refund, String refundStatus, String token) {
        this.refund = refund;
        this.refundId = refund.RefundId__c;
        this.refundStatus = refundStatus;
        this.token = token;
        this.invoiceId = refund.InvoiceId__c;
    }

    public void execute(QueueableContext context) {
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        TrainingInvoice__c invoice = TrainingInvoiceQueries.queryInvoiceByInvoiceId(invoiceId);
        Logger logger = new Logger();

        if(refundStatus == REFUND_STATUS_REFUNDED) {
            refund.Status__c = REFUND_STATUS_REFUNDED;
            try {
                refund.verificationId__c = RefundCallout.doRefundVerificationCalloutForParticipant(refundId, token);
            } catch(Exception e) {
                logger.logException(e);
            }

            invoice.Status__c = REFUND_STATUS_REFUNDED;

            emails.add(EmailService.createParticipantRefundProcessedEmail(invoice));
        } else {
            refund.Status__c = REFUND_STATUS_FAILED;

            emails.add(EmailService.createRefundOrderFailedEmail(refund));

            logger.logRefundOrderFailed(refund);
        }

        update refund;
        update invoice;

        if(!emails.isEmpty()) {
            Messaging.sendEmail(emails);
        }
    }

}