force-app/main/default/objects/Restaurant__c/Restaurant__c.object-meta.xml
<CustomObject>
    <label>Restaurant</label>
    <nameField>
        <label>Restaurant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restaurants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>The training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/NumberOfParticipants__c.field-meta.xml
<CustomField>
    <fullName>NumberOfParticipants__c</fullName>
    <label>Number of Participants</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Restaurant__c.field-meta.xml
<CustomField>
    <fullName>Restaurant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Restaurant</label>
    <referenceTo>Restaurant__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/TrainerContact__c.field-meta.xml
<CustomField>
    <fullName>TrainerContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The trainer that will perform the training</description>
    <label>Trainer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/TrainingCourse__c.field-meta.xml
<CustomField>
    <fullName>TrainingCourse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Course</label>
    <referenceTo>TrainingCourse__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/TrainingDuration__c.field-meta.xml
<CustomField>
    <fullName>TrainingDuration__c</fullName>
    <inlineHelpText>Duration is calculated as follows: Number Of Days * Training Hours Per Day + Preparation Time + Review Time</inlineHelpText>
    <label>Training Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/UniqueId__c.field-meta.xml
<CustomField>
    <fullName>UniqueId__c</fullName>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingCourse__c/TrainingCourse__c.object-meta.xml
<CustomObject>
    <label>Training Course</label>
    <nameField>
        <label>Training Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Integrations/TrainingRestService.cls
@RestResource(UrlMapping='/Trainings/*')
global with sharing class TrainingRestService implements SObjectServiceInterface {

    public virtual class TrainingRestServiceException extends Exception {}
    public class InvalidTrainingRecordDataException extends TrainingRestServiceException {}

    @HttpGet
    global static Training__c getTrainingById() {
        RestRequest request = RestContext.request;

        String trainingId = request.requestURI.substring(request.requestURI.lastIndexOf('/') + 1);
        String escapedTrainingId = String.escapeSingleQuotes(trainingId);
 
        String querySelect = 'SELECT Name, TrainingDuration__c, Status__c, TrainerContact__r.FirstName, ' + 
            'TrainerContact__r.LastName, StartDate__c, EndDate__c, NumberOfParticipants__c ';
        String queryFrom = 'FROM Training__c ';
        String queryWhere = '';

        if(trainingId.length() >= 18) {
            queryWhere = 'WHERE Id = :escapedTrainingId';
        } else {
            queryWhere = 'WHERE UniqueId__c = :escapedTrainingId';
        }

        String query = querySelect + queryFrom + queryWhere;

        return Database.query(query);
    }

    @HttpPost
    global static ID createTraining(
        String name, 
        String trainerContact, 
        String trainingCourse, 
        String restaurant, 
        Datetime startDate, 
        Datetime endDate
    ) {
        Training__c training = new Training__c();

        training.Name = name;
        training.TrainerContact__c = trainerContact;
        training.TrainingCourse__c = trainingCourse;
        training.Restaurant__c = restaurant;
        training.StartDate__c = startDate;
        training.EndDate__c = endDate;

        if(!validateObject(training)) {
            throw new InvalidTrainingRecordDataException();
        }

        formatRecord(training);
        insert training;
    
        return training.Id;
    }

    public static Boolean validateObject(SObject record) {
        if(record == null || !(record instanceof Training__c)) {
            return false;
        }

        return ((Training__c) record).Name != null && 
            ((Training__c) record).TrainerContact__c != null && 
            ((Training__c) record).TrainingCourse__c != null && 
            ((Training__c) record).Restaurant__c != null && 
            ((Training__c) record).StartDate__c != null && 
            ((Training__c) record).EndDate__c != null;
    }

    public static void formatRecord(SObject record) {
        if(record instanceof Training__c) {
            Training__c training = (Training__c) record;

            List<String> splitNames = training.Name.split(' ');
            String formattedName = '';

            for(String name : splitNames) {
                if(name != '') {
                    formattedName += name.trim().capitalize() + ' ';
                }
            }

            training.Name = formattedName.trim();
        }
    }

}