force-app/main/default/objects/Restaurant__c/Restaurant__c.object-meta.xml
<CustomObject>
    <label>Restaurant</label>
    <nameField>
        <label>Restaurant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restaurants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Restaurant__c/fields/AverageMealCost__c.field-meta.xml
<CustomField>
    <fullName>AverageMealCost__c</fullName>
    <description>The average meal cost per person.</description>
    <label>Average Meal Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Restaurant__c/fields/CommissionRate__c.field-meta.xml
<CustomField>
    <fullName>CommissionRate__c</fullName>
    <description>The commission rate agreed upon between the restaurant and the training company.</description>
    <label>Commission Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>The training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Restaurant__c.field-meta.xml
<CustomField>
    <fullName>Restaurant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Restaurant</label>
    <referenceTo>Restaurant__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/TrainerContact__c.field-meta.xml
<CustomField>
    <fullName>TrainerContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The trainer that will perform the training</description>
    <label>Trainer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/TrainingCourse__c.field-meta.xml
<CustomField>
    <fullName>TrainingCourse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Course</label>
    <referenceTo>TrainingCourse__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingCourse__c/TrainingCourse__c.object-meta.xml
<CustomObject>
    <label>Training Course</label>
    <nameField>
        <label>Training Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TrainingTriggerHandlerTest.cls
@IsTest
public with sharing class TrainingTriggerHandlerTest {

    @TestSetup
    static void setup() {
        TrainingCourse__c trainingCourse = new TrainingCourse__c(Name = 'Test Trigger Training');
        insert(trainingCourse);

        Restaurant__c restaurant1 = new Restaurant__c();
        Restaurant__c restaurant2 = new Restaurant__c();

        restaurant1.Name = 'Tam O\'Shanter';
        restaurant1.CommissionRate__c = 15;
        restaurant1.AverageMealCost__c = 55;

        restaurant2.Name = 'The Apple Pan';
        restaurant2.CommissionRate__c = 20;
        restaurant2.AverageMealCost__c = 30;

        insert new List<Restaurant__c> {restaurant1, restaurant2};

        Contact contact1 = new Contact(LastName = 'Trainer-One');
        Contact contact2 = new Contact(LastName = 'Trainer-Two');
        insert new List<Contact> {contact1, contact2};

        Training__c training1 = new Training__c();
        Training__c training2 = new Training__c();
        Training__c training3 = new Training__c();
        Training__c training4 = new Training__c();
        Training__c training5 = new Training__c();
        
        training1.Name = 'Brand New Training One';
        training1.Restaurant__c = restaurant1.Id;
        training1.StartDate__c = System.today();
        training1.EndDate__c = System.today();
        training1.TrainerContact__c = contact1.Id;
        training1.TrainingCourse__c = trainingCourse.Id;

        training2.Name = 'Brand New Training Two';
        training2.Restaurant__c = restaurant1.Id;
        training2.StartDate__c = System.today();
        training2.EndDate__c = System.today().addDays(9);
        training2.TrainerContact__c = contact1.Id;
        training2.TrainingCourse__c = trainingCourse.Id;
        
        training3.Name = 'Brand New Training Three';
        training3.Restaurant__c = restaurant1.Id;
        training3.StartDate__c = System.today().addMonths(1);
        training3.EndDate__c = System.today().addMonths(1);
        training3.TrainerContact__c = contact1.Id;
        training3.TrainingCourse__c = trainingCourse.Id;

        training4.Name = 'Chocolate Training Four';
        training4.Restaurant__c = restaurant2.Id;
        training4.StartDate__c = System.today();
        training4.EndDate__c = System.today();
        training4.TrainerContact__c = contact1.Id;
        training4.TrainingCourse__c = trainingCourse.Id;

        training5.Name = 'Chocolate Training Five';
        training5.Restaurant__c = restaurant2.Id;
        training5.StartDate__c = System.today();
        training5.EndDate__c = System.today();
        training5.TrainerContact__c = contact1.Id;
        training5.TrainingCourse__c = trainingCourse.Id;

        insert new List<Training__c>{training1, training2, training3, training4, training5};
    }

    @IsTest
    static void beforeInsertTrigger_UnitTest() {
        List<Training__c> trainings = new List<Training__c>();

        Contact contact = [SELECT Id, Name FROM Contact LIMIT 1];
        Restaurant__c restaurant = [SELECT Id, Name FROM Restaurant__c WHERE Name LIKE 'Tam%'];
        trainingCourse__c trainingCourse = [SELECT Id, Name FROM trainingCourse__c WHERE Name = 'Test Trigger Training'];


        for(Integer i = 1; i <= 5; i++) {
            Training__c training = new Training__c();

            training.Name = 'Test Trigger Training ' + i;
            training.Restaurant__c = restaurant.Id;
            training.StartDate__c = System.today().addMonths(1);
            training.EndDate__c = System.today().addMonths(1);
            training.TrainerContact__c = contact.Id;
            training.TrainingCourse__c = trainingCourse.Id;

            trainings.add(training);
        }

        Test.startTest();
        insert trainings;
        Test.stopTest();

        List<Training__c> trainingsInserted; // = [
        //     SELECT Id, RestaurantCommissionForecast__c 
        //     FROM Training__c 
        //     WHERE Id IN :trainings
        // ];

        Assert.areEqual(trainings.size(), trainingsInserted.size());
        for(Training__c training : trainingsInserted) {
            // Assert.areEqual(6.60, training.RestaurantCommissionForecast__c);
        }
    }

    @IsTest
    static void beforeInsertTrigger_lazy() {
        Restaurant__c restaurant1 = new Restaurant__c();
        restaurant1.Name = 'Tam O\'Shanter';
        restaurant1.CommissionRate__c = 15;
        restaurant1.AverageMealCost__c = 55;
        insert restaurant1;

        Training__c training = new Training__c(Restaurant__c = restaurant1.Id);

        Test.startTest();
        insert training;
        Test.stopTest();

        // Training__c result = [
        //     SELECT Id, RestaurantCommissionForecast__c 
        //     FROM Training__c 
        //     WHERE Id = :training.Id
        //     LIMIT 1
        // ];

        // Assert.areEqual(6.60, result.RestaurantCommissionForecast__c);
    }

    static void insertTasksForTrainings_lazy() {
        List<Training__c> newList = new List<Training__c> {new Training__c(Name = 'uniqueName')};
        String subject = '';
        insert newList;
        TrainingService trainingService = new TrainingService();
        Test.startTest();
        trainingService.insertTasksForTrainings(newList, null);
        Test.stopTest();

        List<Task> tasks = [SELECT ActivityDate, Status FROM Task WHERE Subject = :subject];
        Assert.areEqual(1, tasks.size());

        Task task = tasks.get(0);
        Assert.areEqual(System.today(), task.ActivityDate);
        Assert.areEqual('Not started', task.Status);
    }

    @IsTest
    static void afterInsertTrigger_UnitTest() {
        List<Training__c> trainings = new List<Training__c>();

        Contact contact = [SELECT Id, Name FROM Contact LIMIT 1];
        Restaurant__c restaurant = [SELECT Id, Name FROM Restaurant__c WHERE Name LIKE 'The%'];
        trainingCourse__c trainingCourse = [SELECT Id, Name FROM trainingCourse__c WHERE Name = 'Test Trigger Training'];

        for(Integer i = 1; i <= 5; i++) {
            Training__c training = new Training__c();

            training.Name = 'Test Trigger Training ' + i;
            training.Restaurant__c = restaurant.Id;
            training.StartDate__c = System.today().addMonths(1);
            training.EndDate__c = System.today().addMonths(1);
            training.TrainerContact__c = contact.Id;
            training.TrainingCourse__c = trainingCourse.Id;

            trainings.add(training);
        }

        insert trainings;

        Test.startTest();
        TrainingTriggerHandler.afterInsert(trainings, null);
        Test.stopTest();

        // List<Task> tasksInserted = [
        //     SELECT Id, RestaurantCommissionForecast__c  
        //     FROM Task 
        //     WHERE Subject IN :trainings.Name
        // ];

        // Assert.areEqual(trainings.size(), trainingsInserted.size());
        // Assert.areEqual(6.60, trainingsInserted.get(0).RestaurantCommissionForecast__c);
    }
}