force-app/main/default/objects/Restaurant__c/Restaurant__c.object-meta.xml
<CustomObject>
    <label>Restaurant</label>
    <nameField>
        <label>Restaurant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restaurants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Restaurant__c/fields/AverageMealCost__c.field-meta.xml
<CustomField>
    <fullName>AverageMealCost__c</fullName>
    <description>The average meal cost per person.</description>
    <label>Average Meal Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Restaurant__c/fields/CommissionRate__c.field-meta.xml
<CustomField>
    <fullName>CommissionRate__c</fullName>
    <description>The commission rate agreed upon between the restaurant and the training company.</description>
    <label>Commission Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>The training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Restaurant__c.field-meta.xml
<CustomField>
    <fullName>Restaurant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Restaurant</label>
    <referenceTo>Restaurant__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/TrainerContact__c.field-meta.xml
<CustomField>
    <fullName>TrainerContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The trainer that will perform the training</description>
    <label>Trainer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/TrainingCourse__c.field-meta.xml
<CustomField>
    <fullName>TrainingCourse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Course</label>
    <referenceTo>TrainingCourse__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/UniqueId__c.field-meta.xml
<CustomField>
    <fullName>UniqueId__c</fullName>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingCourse__c/TrainingCourse__c.object-meta.xml
<CustomObject>
    <label>Training Course</label>
    <nameField>
        <label>Training Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Tests/TrainingRestServiceTest.cls
@IsTest
public with sharing class TrainingRestServiceTest {

    @TestSetup
    static void setup() {
        Restaurant__c restaurant = new Restaurant__c();
        restaurant.Name = 'Tam O\'Shanter';
        restaurant.CommissionRate__c = 15;
        restaurant.AverageMealCost__c = 55;
        insert restaurant;

        Contact contact = new Contact(LastName = 'Trainer-One');
        insert contact;

        TrainingCourse__c trainingCourse = new TrainingCourse__c(Name = 'Test Rest Resources Course');
        insert(trainingCourse);

        Training__c  training = new Training__c();
        training.Name = 'Rest Training Beginner';
        training.TrainerContact__c = contact.Id;
        training.TrainingCourse__c = trainingCourse.Id;
        training.Restaurant__c = restaurant.Id;
        training.StartDate__c = System.today().addDays(1);
        training.EndDate__c = System.today().addDays(2);
        insert training;
    }

    @IsTest
    static void getTrainingById_UnitTest_TrainingId() {
        Id trainingId = getTestTrainingId();

        RestRequest request = new RestRequest();
        request.requestUri =
            'https://curious-hawk-3uzcps-dev-ed.trailblaze.my.salesforce.com/services/apexrest/Trainings/' + trainingId;
        request.httpMethod = 'GET';
        RestContext.request = request;

        Training__c training = TrainingRestService.getTrainingById();

        Assert.isNotNull(training);
        Assert.areEqual('Rest Training Beginner', training.Name);
    }

    @IsTest
    static void getTrainingById_UnitTest_UniqueId() {
        String trainingId = getTestTrainingUniqueId();

        RestRequest request = new RestRequest();
        request.requestUri =
            'https://curious-hawk-3uzcps-dev-ed.trailblaze.my.salesforce.com/services/apexrest/Trainings/' + trainingId;
        request.httpMethod = 'GET';
        RestContext.request = request;

        Training__c training = TrainingRestService.getTrainingById();

        Assert.isNotNull(training);
        Assert.areEqual('Rest Training Beginner', training.Name);
    }

    @IsTest
    static void createTraining_UnitTest() {
        Restaurant__c restaurant = [SELECT Id FROM Restaurant__c LIMIT 1];
        Contact contact = [SELECT Id FROM Contact LIMIT 1];
        TrainingCourse__c trainingCourse = [SELECT Id FROM TrainingCourse__c LIMIT 1];

        ID trainingId = TrainingRestService.createTraining(
            'Rest Training Intermediate',
            String.valueOf(contact.Id),
            String.valueOf(trainingCourse.Id),
            String.valueOf(restaurant.Id),
            System.today(),
            System.today().addDays(1)
        );

        Assert.isNotNull(trainingId != null);

        Training__c insertedTraining = [SELECT Id, Name FROM Training__c WHERE Id = :trainingId];
        Assert.isNotNull(insertedTraining);
        Assert.areEqual('Rest Training Intermediate', insertedTraining.Name);
    }

    @IsTest
    static void createTraining_UnitTest_InvalidFields() {
        Contact contact = [SELECT Id FROM Contact LIMIT 1];

        try {
            ID trainingId = TrainingRestService.createTraining(
                'Rest Training Intermediate',
                String.valueOf(contact.Id),
                null,
                null,
                System.today(),
                System.today().addDays(1)
            );

            Assert.fail();
        } catch(Exception e) {
            Assert.isTrue(true);
        }
    }

    static Id getTestTrainingId() {
        Training__c training = [SELECT Id FROM Training__c LIMIT 1];

        return training.Id;
    }

    static String getTestTrainingUniqueId() {
        Training__c training = [SELECT UniqueId__c FROM Training__c LIMIT 1];

        return training.UniqueId__c;
    }

}