force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>The training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingInvoice__c/TrainingInvoice__c.object-meta.xml
<CustomObject>
    <label>Training Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Training Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingInvoice__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <inlineHelpText>Total isolated tax amount calculated from the total price.</inlineHelpText>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Training Invoices</relationshipLabel>
    <relationshipName>TrainingInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingInvoiceLineItem__c/TrainingInvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Training Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{000000}</displayFormat>
        <label>Training Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingInvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>TrainingInvoice__c</referenceTo>
    <relationshipLabel>Training Invoice Line Items</relationshipLabel>
    <relationshipName>TrainingInvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TrainingInvoiceLineItem__c/fields/LineDescription__c.field-meta.xml
<CustomField>
    <fullName>LineDescription__c</fullName>
    <label>Line Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingInvoiceLineItem__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <inlineHelpText>Price of the invoice line item, including taxes, based on the price of the corresponding training line item.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TrainingInvoiceLineItem__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingInvoiceLineItem__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <inlineHelpText>Isolated tax amount based on the tax value of the corresponding training line item.</inlineHelpText>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TrainingInvoiceLineItem__c/fields/TrainingProduct__c.field-meta.xml
<CustomField>
    <fullName>TrainingProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Product</label>
    <referenceTo>TrainingProduct__c</referenceTo>
    <relationshipLabel>Training Invoice Line Items</relationshipLabel>
    <relationshipName>TrainingInvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingLineItem__c/TrainingLineItem__c.object-meta.xml
<CustomObject>
    <label>Training Line Item</label>
    <nameField>
        <label>Training Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingLineItem__c/fields/LineDescription__c.field-meta.xml
<CustomField>
    <fullName>LineDescription__c</fullName>
    <defaultValue>&apos;Product description will be auto-filled on save&apos;</defaultValue>
    <label>Line Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingLineItem__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <inlineHelpText>Price of the line item, including taxes. Leave blank to auto-fill from the product price on record creation or enter a new price.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TrainingLineItem__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <defaultValue>&apos;Product code will be auto-filled on save&apos;</defaultValue>
    <label>Product Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingLineItem__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <formula>Price__c * ( $CustomMetadata.TrainingVATRateMetadata__mdt.StandardRate.Tax__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Isolated tax amount calculated from the price.</inlineHelpText>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TrainingLineItem__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Training Line Items</relationshipLabel>
    <relationshipName>TrainingLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingLineItem__c/fields/TrainingProduct__c.field-meta.xml
<CustomField>
    <fullName>TrainingProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Product</label>
    <referenceTo>TrainingProduct__c</referenceTo>
    <relationshipLabel>Training Line Items</relationshipLabel>
    <relationshipName>TrainingLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingProduct__c/TrainingProduct__c.object-meta.xml
<CustomObject>
    <label>Training Product</label>
    <nameField>
        <label>Training Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingProduct__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Product Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Business/Service/TrainingInvoiceService.cls
public with sharing class TrainingInvoiceService {

    /**
     * This method is part of the Training invoice management process. It is invoked from the afterInsert method 
     * on the trigger handler class, "TrainingInvoiceTriggerHandler." It creates invoice line items from the 
     * corresponding training line items.
     * 
     * @param newlist   List of training invoices
     * @param oldMap    Old map of training invoices, always null
     */
    public void createInvoiceLineItemsFromTrainingLineItems(
        List<TrainingInvoice__c> newList, 
        Map<Id, TrainingInvoice__c> oldMap
    ) {
        Set<Id> trainingIds = new Set<Id>();

        for(TrainingInvoice__c trainingInvoice : newList) {
            trainingIds.add(trainingInvoice.Training__c);
        }

        Map<Id, Training__c> trainingsWithLineItems = new Map<Id, Training__c>(
            TrainingQueries.queryTrainingsWithLineItemsById(trainingIds)
        );

        List<TrainingInvoiceLineItem__c> invoiceLineItems = new List<TrainingInvoiceLineItem__c>();

        for(TrainingInvoice__c invoice : newList) {
            Training__c training = trainingsWithLineItems.get(invoice.Training__c);
            List<TrainingLineItem__c> trainingLineItems = training.TrainingLineItems__r;

            for(TrainingLineItem__c trainingLineItem : trainingLineItems) {
                invoiceLineItems.add(createTrainingInvoiceLineItem(trainingLineItem, invoice.Id));
            }
        }

        try {
            insert invoiceLineItems;
        } catch(Exception e) {
            Logger logger = new Logger();
            logger.logException(e);
        }
    }

    private TrainingInvoiceLineItem__c createTrainingInvoiceLineItem(TrainingLineItem__c trainingLineItem, Id invoiceId) {
        TrainingInvoiceLineItem__c invoiceLineItem = new TrainingInvoiceLineItem__c();

        invoiceLineItem.Invoice__c = invoiceId;
        invoiceLineItem.TrainingProduct__c = trainingLineItem.TrainingProduct__c;
        invoiceLineItem.LineDescription__c = trainingLineItem.LineDescription__c;
        invoiceLineItem.ProductCode__c = trainingLineItem.ProductCode__c;
        invoiceLineItem.Price__c = trainingLineItem.Price__c;
        invoiceLineItem.Tax__c = trainingLineItem.Tax__c;

        return invoiceLineItem;
    }

}