force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>The training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <inlineHelpText>Total price of the course, including taxes.</inlineHelpText>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/TotalTax__c.field-meta.xml
<CustomField>
    <fullName>TotalTax__c</fullName>
    <inlineHelpText>Total isolated tax amount calculated from the total price.</inlineHelpText>
    <label>Total Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TrainingLineItem__c/TrainingLineItem__c.object-meta.xml
<CustomObject>
    <label>Training Line Item</label>
    <nameField>
        <label>Training Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingLineItem__c/fields/LineDescription__c.field-meta.xml
<CustomField>
    <fullName>LineDescription__c</fullName>
    <defaultValue>&apos;Product description will be auto-filled on save&apos;</defaultValue>
    <label>Line Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingLineItem__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <inlineHelpText>Price of the line item, including taxes. Leave blank to auto-fill from the product price on record creation or enter a new price.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TrainingLineItem__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <defaultValue>&apos;Product code will be auto-filled on save&apos;</defaultValue>
    <label>Product Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingLineItem__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <formula>Price__c * ( $CustomMetadata.TrainingVATRateMetadata__mdt.StandardRate.Tax__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Isolated tax amount calculated from the price.</inlineHelpText>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TrainingLineItem__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Training Line Items</relationshipLabel>
    <relationshipName>TrainingLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingLineItem__c/fields/TrainingProduct__c.field-meta.xml
<CustomField>
    <fullName>TrainingProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Product</label>
    <referenceTo>TrainingProduct__c</referenceTo>
    <relationshipLabel>Training Line Items</relationshipLabel>
    <relationshipName>TrainingLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingProduct__c/TrainingProduct__c.object-meta.xml
<CustomObject>
    <label>Training Product</label>
    <nameField>
        <label>Training Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingProduct__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Product Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingProduct__c/fields/ProductDescription__c.field-meta.xml
<CustomField>
    <fullName>ProductDescription__c</fullName>
    <label>Product Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingProduct__c/fields/ProductPrice__c.field-meta.xml
<CustomField>
    <fullName>ProductPrice__c</fullName>
    <inlineHelpText>Price of the product, including taxes.</inlineHelpText>
    <label>Product Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Business/Service/TrainingLineItemService.cls
public with sharing class TrainingLineItemService {

    /**
     * This method is part of the Training product management process. It is
     * invoked from the beforeInsert method on the trigger handler class,
     * "TrainingLineItemTriggerHandler." It copies product info to the
     * corresponding line item fields.
     * 
     * @param newlist   List of training line items
     * @param oldMap    Old map of training line items, always null
     */
    public void synchronizeLineItemsWithProducts(List<TrainingLineItem__c> newList, Map<Id, TrainingLineItem__c> oldMap) {
        Set<Id> productIds = new Set<Id>();

        for(TrainingLineItem__c trainingLineItem : newList) {
            productIds.add(trainingLineItem.TrainingProduct__c);
        }

        Map<Id, TrainingProduct__c> trainingProducts = new Map<Id, TrainingProduct__c>(
            TrainingProductQueries.queryTrainingProductsById(productIds)
        );

        for(TrainingLineItem__c lineItem : newList) {
            TrainingProduct__c trainingProduct = trainingProducts.get(lineItem.TrainingProduct__c);
            lineItem = setNewLineItemsWithProductData(lineItem, trainingProduct);
        }
    }

    private TrainingLineItem__c setNewLineItemsWithProductData(TrainingLineItem__c lineItem, TrainingProduct__c product) {
        lineItem.Name = product.Name;
        lineItem.ProductCode__c = product.ProductCode__c;
        lineItem.LineDescription__c = product.ProductDescription__c;

        if(lineItem.Price__c == null) {
            lineItem.Price__c = product.ProductPrice__c;
        }

        return lineItem;
    }

    /**
     * This method is part of the Training product management process. It is
     * invoked from the beforeUpdate method on the trigger handler class,
     * "TrainingLineItemTriggerHandler." If the selected product is changed, it
     * updates the corresponding line item fields.
     * 
     * @param newlist   List of training line items
     * @param oldMap    Old map of training line items, never null
     */
    public void updateLineItemsWithProductChange(List<TrainingLineItem__c> newList, Map<Id, TrainingLineItem__c> oldMap) {
        List<TrainingLineItem__c> lineItemsToProcess = new List<TrainingLineItem__c>();

        Set<Id> productIds = new Set<Id>();

        for(TrainingLineItem__c trainingLineItem : newList) {
            if(filterLineItemsOnProductChanged(trainingLineItem, oldMap) != null) {
                productIds.add(trainingLineItem.TrainingProduct__c);
                lineItemsToProcess.add(trainingLineItem);
            }
        }

        Map<Id, TrainingProduct__c> trainingProducts = new Map<Id, TrainingProduct__c>(
            TrainingProductQueries.queryTrainingProductsById(productIds)
        );

        for(TrainingLineItem__c lineItem : lineItemsToProcess) {
            TrainingProduct__c trainingProduct = trainingProducts.get(lineItem.TrainingProduct__c);
            lineItem = updateLineItemsWithNewProductData(lineItem, trainingProduct);
        }
    }

    private TrainingLineItem__c filterLineItemsOnProductChanged(
        TrainingLineItem__c lineItem, 
        Map<Id, TrainingLineItem__c> oldMap
    ) {
        Boolean isProductChanged = lineItem.TrainingProduct__c != oldMap.get(lineItem.Id).TrainingProduct__c;

        return (isProductChanged) ? lineItem : null;
    }

    private TrainingLineItem__c updateLineItemsWithNewProductData(TrainingLineItem__c lineItem, TrainingProduct__c product) {
        lineItem.Name = product.Name;
        lineItem.ProductCode__c = product.ProductCode__c;
        lineItem.LineDescription__c = product.ProductDescription__c;
        lineItem.Price__c = product.ProductPrice__c;

        return lineItem;
    }

    /**
     * This method is part of the Training price calculation process. It is
     * invoked from the afterInsert method on the trigger handler class,
     * "TrainingLineItemTriggerHandler." It adds product line item prices and
     * taxes and updates the respective fields on trainings.
     * 
     * @param newlist   List of training line items
     * @param oldMap    Old map of training line items, always null
     */
    public void calculateTotalPriceAndTaxOnTrainings(List<TrainingLineItem__c> newList, Map<Id, TrainingLineItem__c> oldMap) {
        Set<Id> trainingIds = new Set<Id>();

        for(TrainingLineItem__c trainingLineItem : newList) {
            trainingIds.add(trainingLineItem.Training__c);
        }

        List<Training__c> trainingsWithLineItems = TrainingQueries.queryTrainingsWithLineItemsById(trainingIds);

        for(Training__c training : trainingsWithLineItems) {
            training.TotalPrice__c = 0.0;
            training.TotalTax__c = 0.0;

            for(TrainingLineItem__c trainingLineItem : training.TrainingLineItems__r) {
                training.TotalPrice__c += trainingLineItem.Price__c;
                training.TotalTax__c += trainingLineItem.Tax__c;
            }
        }

        if(!trainingsWithLineItems.isEmpty()) {
            update trainingsWithLineItems;
        }
    }

    /**
     * This method is part of the Training price calculation process. It is
     * invoked from the afterUpdate method on the trigger handler class,
     * "TrainingLineItemTriggerHandler." If line item prices and taxes are updated, 
     * it recalculates the sums and and updates the respective fields on trainings.
     * 
     * @param newlist   List of training line items
     * @param oldMap    Old map of training line items, never null
     */
    public void updateTotalPriceAndTaxOnTrainings(List<TrainingLineItem__c> newList, Map<Id, TrainingLineItem__c> oldMap) {
        List<TrainingLineItem__c> lineItemsToProcess = new List<TrainingLineItem__c>();

        Set<Id> trainingIds = new Set<Id>();

        for(TrainingLineItem__c trainingLineItem : newList) {
            if(filterLineItemsOnPriceChanged(trainingLineItem, oldMap) != null) {
                trainingIds.add(trainingLineItem.Training__c);
            }
        }

        if(trainingIds.isEmpty()) {
            return;
        }

        List<Training__c> trainingsWithLineItems = TrainingQueries.queryTrainingsWithLineItemsById(trainingIds);

        for(Training__c training : trainingsWithLineItems) {
            training.TotalPrice__c = 0.0;
            training.TotalTax__c = 0.0;

            for(TrainingLineItem__c trainingLineItem : training.TrainingLineItems__r) {
                training.TotalPrice__c += trainingLineItem.Price__c;
                training.TotalTax__c += trainingLineItem.Tax__c;
            }
        }

        if(!trainingsWithLineItems.isEmpty()) {
            update trainingsWithLineItems;
        }
    }

    private TrainingLineItem__c filterLineItemsOnPriceChanged(
        TrainingLineItem__c lineItem, 
        Map<Id, TrainingLineItem__c> oldMap
    ) {
        Boolean isPriceChanged = lineItem.Price__c != oldMap.get(lineItem.Id).Price__c;

        return (isPriceChanged) ? lineItem : null;
    }

}