force-app/main/default/objects/Contact/fields/CanBookForOthers__c.field-meta.xml
<CustomField>
    <fullName>CanBookForOthers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Can Book For Others</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/ErpId__c.field-meta.xml
<CustomField>
    <fullName>ErpId__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>The training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SendParticipantToERPTest.cls
@IsTest
public with sharing class SendParticipantToERPTest {

    @TestSetup
    static void setup() {
        Test.setMock(HttpCalloutMock.class, new PaymentLinkHttpCalloutMock());

        Training__c training = new Training__c();
        training.Name = 'Test Callout Training';
        training.StartDate__c = System.today().addMonths(1);
        training.EndDate__c = System.today().addMonths(1);
        insert training;

        Contact contact = new Contact(LastName = 'Participant', CanBookForOthers__c = true, Email = 'e@mail.com');
        List<Contact> contacts = new List<Contact> {contact};
        insert contacts;

        Participant__c participant = new Participant__c(Contact__c = contact.Id, Training__c = training.Id);
        insert participant;
    }

    @IsTest
    static void sendParticipantsToERP_UnitTest() {
        Test.setMock(HttpCalloutMock.class, new ERPCalloutHttpCalloutMock());

        Participant__c participant = [SELECT Id FROM Participant__c LIMIT 1];
        List<Id> participantIds = new List<Id> {participant.Id};

        Test.startTest();
        SendParticipantToERP.sendParticipantsToERP(participantIds);
        Test.stopTest();

        Participant__c updatedParticipant = [SELECT Id, ErpId__c FROM Participant__c LIMIT 1];
        Assert.areEqual(ERPCalloutHttpCalloutMock.ERP_ID, updatedParticipant.ErpId__c);
    }

    @IsTest
    static void parseErpId_UnitTest() {
        String reponseBody = '{"erpId":"' + ERPCalloutHttpCalloutMock.ERP_ID + '"}';
        String expectedId = ERPCalloutHttpCalloutMock.ERP_ID;

        Test.startTest();
        String actualId = SendParticipantToERP.parseErpId(reponseBody);
        Test.stopTest();

        Assert.areEqual(expectedId, actualId);
    }

    @IsTest
    static void parseErpId_UnitTest_noErpIdKey() {
        String reponseBody = '{"ErpsId":"' + ERPCalloutHttpCalloutMock.ERP_ID + '"}';
        String expectedId = '';

        Test.startTest();
        String actualId = SendParticipantToERP.parseErpId(reponseBody);
        Test.stopTest();

        Assert.areEqual(expectedId, actualId);
    }

}