force-app/main/default/objects/Contact/fields/CanBookForOthers__c.field-meta.xml
<CustomField>
    <fullName>CanBookForOthers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Can Book For Others</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Queue</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Restaurant__c/Restaurant__c.object-meta.xml
<CustomObject>
    <label>Restaurant</label>
    <nameField>
        <label>Restaurant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restaurants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Restaurant__c/fields/AverageMealCost__c.field-meta.xml
<CustomField>
    <fullName>AverageMealCost__c</fullName>
    <description>The average meal cost per person.</description>
    <label>Average Meal Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Restaurant__c/fields/CommissionRate__c.field-meta.xml
<CustomField>
    <fullName>CommissionRate__c</fullName>
    <description>The commission rate agreed upon between the restaurant and the training company.</description>
    <label>Commission Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>The training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Restaurant__c.field-meta.xml
<CustomField>
    <fullName>Restaurant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Restaurant</label>
    <referenceTo>Restaurant__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/TrainingInvoice__c.object-meta.xml
<CustomObject>
    <label>Training Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Training Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingInvoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrainingInvoice__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Training Invoices</relationshipLabel>
    <relationshipName>TrainingInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/TrainingRefund__c.object-meta.xml
<CustomObject>
    <label>Training Refund</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Training Refund Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Refunds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingRefund__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <label>Invoice Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Training Refunds</relationshipLabel>
    <relationshipName>TrainingRefunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Schedule Change</fullName>
            </value>
            <value>
                <fullName>Course Cancellation</fullName>
            </value>
            <value>
                <fullName>Participant Withdrawal</fullName>
            </value>
            <value>
                <fullName>Technical Issues</fullName>
            </value>
            <value>
                <fullName>Billing Error</fullName>
            </value>
            <value>
                <fullName>Other (Specify in Comments)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/RefundDate__c.field-meta.xml
<CustomField>
    <fullName>RefundDate__c</fullName>
    <label>Refund Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/RefundId__c.field-meta.xml
<CustomField>
    <fullName>RefundId__c</fullName>
    <label>Refund Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrainingRefund__c/fields/TrainingInvoice__c.field-meta.xml
<CustomField>
    <fullName>TrainingInvoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Training Invoice</label>
    <referenceTo>TrainingInvoice__c</referenceTo>
    <relationshipLabel>Training Refunds</relationshipLabel>
    <relationshipName>TrainingRefunds</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Tests/RefundPollingQueueableTest.cls
@IsTest
private class RefundPollingQueueableTest {

    @TestSetup
    static void setup() {
        Restaurant__c restaurant = new Restaurant__c();
        restaurant.Name = 'Tam O\'Shanter';
        restaurant.CommissionRate__c = 15;
        restaurant.AverageMealCost__c = 55;
        insert restaurant;

        Training__c training = new Training__c();
        training.Name = 'Test Trigger Training';
        training.Restaurant__c = restaurant.Id;
        training.StartDate__c = System.today().addMonths(1);
        training.EndDate__c = System.today().addMonths(1);
        insert training;

        Contact contact = new Contact(LastName = 'Participant-One', CanBookForOthers__c = true, Email = 'e@mail.com');
        insert contact;

        Participant__c participant = new Participant__c(Contact__c = contact.Id, Training__c = training.Id);
        insert participant;

        TrainingInvoice__c invoice = new TrainingInvoice__c();
        invoice.InvoiceDate__c = System.today();
        invoice.InvoiceId__c = '657c33e3c01b55ac1cfd6f59';
        invoice.Status__c = InvoicePostProcessingQueueable.INVOICE_STATUS_CREATED;
        invoice.Participant__c = participant.Id;
        invoice.Training__c = participant.Training__c;
        insert invoice;

        TrainingRefund__c refund = new TrainingRefund__c();
        refund.TrainingInvoice__r = new TrainingInvoice__c(InvoiceId__c = invoice.InvoiceId__c );
        refund.Amount__c = 190;
        refund.Participant__c = participant.Id;
        refund.Reason__c = 'Technical Issues';
        refund.RefundDate__c = System.today();
        refund.Status__c = ParticipantService.REFUND_STATUS_PENDING;
        refund.RefundId__c = RefundCalloutHttpCalloutMock.REFUND_RESPONSE_ID;
        insert refund;
    }

    @IsTest
    static void enqueuePollingStatusRefundedFirstTry_UnitTest() {
        Test.setMock(HttpCalloutMock.class, new RefundCalloutHttpCalloutMock());

        String refundId = RefundCalloutHttpCalloutMock.REFUND_RESPONSE_ID;
        TrainingRefund__c refund = TrainingRefundQueries.queryRefundByRefundId(refundId);

        RefundCallout.RefundResponseBody refundResponse = new RefundCallout.RefundResponseBody();
        refundResponse.status = ParticipantService.REFUND_RESPONSE_STATUS_INITIATED;
        refundResponse.refund_id = refundId;
        refundResponse.token = InvoiceCalloutHttpCalloutMock.AUTH_RESPONSE_TOKEN;

        Test.startTest();
        RefundPollingQueueable.DO_CHAIN_JOBS_FOR_NON_TEST_CONTEXT = false;
        Id jobId = System.enqueueJob(new RefundPollingQueueable(refundResponse));
        Test.stopTest();

        AsyncApexJob job = [SELECT Id, Status, JobType, ApexClass.Name FROM AsyncApexJob WHERE Id = :jobId];

        Assert.isNotNull(job);
        Assert.areEqual('RefundPollingQueueable', job.ApexClass.Name);
        Assert.areEqual('Completed', job.Status);
        Assert.areEqual('Queueable', job.JobType);
    }

    @IsTest
    static void enqueuePollingStatusFailedFirstTry_UnitTest() {
        Test.setMock(HttpCalloutMock.class, new RefundCalloutHttpCalloutMock());

        String refundId = RefundCalloutHttpCalloutMock.REFUND_RESPONSE_ID;
        TrainingRefund__c refund = TrainingRefundQueries.queryRefundByRefundId(refundId);

        RefundCallout.RefundResponseBody refundResponse = new RefundCallout.RefundResponseBody();
        refundResponse.status = ParticipantService.REFUND_RESPONSE_STATUS_INITIATED;
        refundResponse.refund_id = refundId;
        refundResponse.token = InvoiceCalloutHttpCalloutMock.AUTH_RESPONSE_TOKEN;

        Test.startTest();
        RefundPollingQueueable.DO_CHAIN_JOBS_FOR_NON_TEST_CONTEXT = false;
        RefundCalloutHttpCalloutMock.IS_STATUS_REFUNDED = false;
        Id jobId = System.enqueueJob(new RefundPollingQueueable(refundResponse));
        Test.stopTest();

        AsyncApexJob job = [SELECT Id, Status, JobType, ApexClass.Name FROM AsyncApexJob WHERE Id = :jobId];

        Assert.isNotNull(job);
        Assert.areEqual('RefundPollingQueueable', job.ApexClass.Name);
        Assert.areEqual('Completed', job.Status);
        Assert.areEqual('Queueable', job.JobType);
    }

    @IsTest
    static void enqueuePollingStatusFailedThirdTry_UnitTest() {
        Test.setMock(HttpCalloutMock.class, new RefundCalloutHttpCalloutMock());

        String refundId = RefundCalloutHttpCalloutMock.REFUND_RESPONSE_ID;
        TrainingRefund__c refund = TrainingRefundQueries.queryRefundByRefundId(refundId);

        RefundCallout.RefundResponseBody refundResponse = new RefundCallout.RefundResponseBody();
        refundResponse.status = ParticipantService.REFUND_RESPONSE_STATUS_INITIATED;
        refundResponse.refund_id = refundId;
        refundResponse.token = InvoiceCalloutHttpCalloutMock.AUTH_RESPONSE_TOKEN;

        Test.startTest();
        RefundPollingQueueable.DO_CHAIN_JOBS_FOR_NON_TEST_CONTEXT = false;
        RefundPollingQueueable.SET_RETRY_COUNT_3_FOR_TEST = true;
        RefundCalloutHttpCalloutMock.IS_STATUS_REFUNDED = false;
        Id jobId = System.enqueueJob(new RefundPollingQueueable(refundResponse));
        Test.stopTest();

        AsyncApexJob job = [SELECT Id, Status, JobType, ApexClass.Name FROM AsyncApexJob WHERE Id = :jobId];

        Assert.isNotNull(job);
        Assert.areEqual('RefundPollingQueueable', job.ApexClass.Name);
        Assert.areEqual('Completed', job.Status);
        Assert.areEqual('Queueable', job.JobType);
    }

    @IsTest
    static void enqueuePollingStatusException_UnitTest() {
        Test.setMock(HttpCalloutMock.class, new RefundCalloutHttpCalloutMock());

        String refundId = RefundCalloutHttpCalloutMock.REFUND_RESPONSE_ID;
        TrainingRefund__c refund = TrainingRefundQueries.queryRefundByRefundId(refundId);

        RefundCallout.RefundResponseBody refundResponse = new RefundCallout.RefundResponseBody();
        refundResponse.status = ParticipantService.REFUND_RESPONSE_STATUS_INITIATED;
        refundResponse.refund_id = refundId;
        refundResponse.token = InvoiceCalloutHttpCalloutMock.AUTH_RESPONSE_TOKEN;

        Test.startTest();
        Id jobId = System.enqueueJob(new RefundPollingQueueable(refundResponse));
        Test.stopTest();

        TrainingRefund__c updatedRefund = TrainingRefundQueries.queryRefundByRefundId(refundId);

        Assert.isNotNull(updatedRefund);
        Assert.areEqual(RefundPostProcessingQueueable.REFUND_STATUS_FAILED, updatedRefund.Status__c);

        List<ErrorLog__c> errorLogs = [
            SELECT Id, ClassName__c, MethodName__c, ExceptionMessage__c 
            FROM ErrorLog__c 
            WHERE ClassName__c = 'RefundPollingQueueable'
        ];

        Assert.isNotNull(errorLogs);
        Assert.areEqual(1, errorLogs.size());

        ErrorLog__c resultLog = errorLogs.get(0);
        Assert.isTrue(resultLog.MethodName__c.contains('execute'));
    }

}