force-app/main/default/objects/Contact/fields/CanBookForOthers__c.field-meta.xml
<CustomField>
    <fullName>CanBookForOthers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Can Book For Others</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>The training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Tests/PaymentLinkCalloutTest.cls
@IsTest
private class PaymentLinkCalloutTest {

    @TestSetup
    static void setup() {
        Training__c training = new Training__c();
        training.Name = 'Test Callout Training';
        training.StartDate__c = System.today().addMonths(1);
        training.EndDate__c = System.today().addMonths(1);
        insert training;

        Contact contact = new Contact(LastName = 'Participant', CanBookForOthers__c = true, Email = 'e@mail.com');
        List<Contact> contacts = new List<Contact> {contact};
        insert contacts;
    }
    
    @IsTest
    static void doPaymentCalloutForParticipant_UnitTest() {
        Test.setMock(HttpCalloutMock.class, new PaymentLinkCalloutHttpCalloutMock());

        Contact contact = [SELECT Id FROM Contact LIMIT 1];
        Training__c training = [SELECT Id FROM Training__c LIMIT 1];

        Participant__c participant = new Participant__c(Contact__c = contact.Id, Training__c = training.Id);
        insert participant;

        Test.startTest();
        String responseBody = PaymentLinkCallout.doPaymentCalloutForParticipant(participant);
        Test.stopTest();

        Participant__c updatedParticipant = [SELECT Id, PaymentLink__c FROM Participant__c LIMIT 1];
        Assert.isTrue(responseBody.contains(PaymentLinkCalloutHttpCalloutMock.PAYMENT_LINK));
        Assert.isTrue(responseBody.contains('payer'));
    }

    @IsTest
    static void doPaymentCalloutForParticipant_UnitTest_NullParticipant() {
        Test.setMock(HttpCalloutMock.class, new PaymentLinkCalloutHttpCalloutMock());

        try {
            Test.startTest();
            String responseBody = PaymentLinkCallout.doPaymentCalloutForParticipant(null);
            Test.stopTest();

            Assert.fail();
        } catch(PaymentLinkCallout.NullParticipantException e) {
            Assert.isTrue(true);
        }
    }

    @IsTest
    static void parsePaymentLink_UnitTest() {
        String reponseBody = '{"payer":{"link":"' + PaymentLinkCalloutHttpCalloutMock.PAYMENT_LINK + '"}}';
        String expectedLink = PaymentLinkCalloutHttpCalloutMock.PAYMENT_LINK;

        Test.startTest();
        String actualLink = PaymentLinkCallout.parsePaymentLink(reponseBody);
        Test.stopTest();

        Assert.areEqual(expectedLink, actualLink);
    }

    @IsTest
    static void parsePaymentLink_UnitTest_noPayerKey() {
        String reponseBody = '{"payee":{"link":"' + PaymentLinkCalloutHttpCalloutMock.PAYMENT_LINK + '"}}';
        String expectedLink = '';

        Test.startTest();
        String actualLink = PaymentLinkCallout.parsePaymentLink(reponseBody);
        Test.stopTest();

        Assert.areEqual(expectedLink, actualLink);
    }

    @IsTest
    static void parsePaymentLink_UnitTest_noLinkKey() {
        String reponseBody = '{"payer":{"lnk":"' + PaymentLinkCalloutHttpCalloutMock.PAYMENT_LINK + '"}}';
        String expectedLink = '';

        Test.startTest();
        String actualLink = PaymentLinkCallout.parsePaymentLink(reponseBody);
        Test.stopTest();

        Assert.areEqual(expectedLink, actualLink);
    }

}