force-app/main/default/objects/TrainingRefund__c/TrainingRefund__c.object-meta.xml
<CustomObject>
    <label>Training Refund</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Training Refund Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Refunds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrainingRefund__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Business/Queueable/RefundPollingQueueable.cls
public with sharing class RefundPollingQueueable implements Queueable, Database.AllowsCallouts {

    private static final Integer MAX_RETRY_ATTEMPTS = 3;

    private RefundCallout.RefundResponseBody refundResponse;
    private String refundId;
    private String token;

    public RefundPollingQueueable(RefundCallout.RefundResponseBody refundResponse) {
        this.refundResponse = refundResponse;
        this.refundId = refundResponse.refund_id;
        this.token = refundResponse.token;
    }

    /**
     * This method is part of the Participant refund handling process. It is
     * invoked from the initiateRefundOrder method on the "ParticipantService"
     * class. It accepts a refund id sends a callout to the payment server to
     * generate an refund for the participant.
     */
    public void execute(QueueableContext context) {
        TrainingRefund__c refund = TrainingRefundQueries.queryRefundByRefundId(refundId);
        Integer retryCount = AsyncInfo.getCurrentQueueableStackDepth();
        Integer delayInMinutes;
        String refundStatus = '';

        if(retryCount == 1) {
            delayInMinutes = 3;
        } else {
            delayInMinutes = 10;
        }

        try {
            refundStatus = RefundCallout.doGetRefundCalloutForParticipantByRefundId(refundId, token);
        } catch(Exception e) {
            refund.Status__c = RefundPostProcessingQueueable.REFUND_STATUS_FAILED;

            Logger logger = new Logger();
            logger.logException(e);
        }

        if(retryCount < MAX_RETRY_ATTEMPTS && refundStatus != RefundPostProcessingQueueable.REFUND_STATUS_REFUNDED) {
            System.enqueueJob(new RefundPollingQueueable(refundResponse), delayInMinutes);

            retryCount++;
        } else {
            System.enqueueJob(new RefundPostProcessingQueueable(refund, refundStatus, token));
        }
    } 

}